language: node_js
node_js:
- '8'
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: DLyyufluhmw9NF9as6drddk+Su+jcs7tIvzDJV/+xovsrZnfqhZoQI0q/bamw+NFcJimKtTYCwP+YxoJG6asnSqBMs7V2c+wf1HKBPkB/Ho5tvTa56lVdxKTEZlNozXr2Cx4gQEmwUOAMSOawB4DXgoQtx9BCduhKigoYZ0z1h6QAgmw3D0dFC2OZ3H1i+ugxEXyKoH3vtwnRAPzXb8NX3ANKixiO3jKvaLtrO9H/Fvvq2SK5wMsF1loRDdt1v590ibQdjYyVbV1rDy2GtS+yEyq5zI8VyHHmDl4Aij0TJJ632P+7XCcWrL5q6JZNJZu5YJkcv4zTf5F+BkEG6KkxvMRmPvzMXB4rPq1vSMOYDzlLZgmSv8vnstKgwMYAzSvyFovzHEGyrMI/bXWLbF9YBi8xfuWM5c14SWXRcNiChzNl+PdaNQ4mhHF2XmdU13rzBl1RItq8G/e16ZWA1MT1J2RCNjk34ez7M8GkhOqjZuHU9PvwDWUGcxtSX3lzO6kur0aetMcLh+eqYaeck7clae2KKblg62qg2b1BoV79jf9SbOR7QDWD2VJu4ttlGxq/o6B4A3fWGO+fl0vwB4Al9B94bx7gcnzM5BF5n4GJ88Fx4HdG47bWS/2u9mhm6lNK0x+l9N/Aj+0DCvg4KYF6SJlBxUUmTTzexHzbCBSzbI=
  app: sheltered-headland-53456
  on:
    repo: wjypark94/fridgeful-api
