language: node_js
node_js:
- '8'
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Zqqf2qhWoTDeKzgCWzZst3zEPso0oCO2i1bsamUGRONL7ax+WvLqZHmC18qhN7XrR4+xFBf3P0dLFRs6q81WMR+rY9OEdEaiE08ncI7LIJp5K/Sj+ZSocBg6Gp/bzvnXY+gJW6S4FzQST0vN40Yku9VE0wvurqJXIm4EDl3exrKLxd4cYA6kej1CpWLXCWVKjvJr9zVx6cJvel62wJJ4JEzrsiYeC+FDp2ozUrtlCJ1aOAHUeHMLvQDS3wWI+xFrotymu5+3O7gqIWdi1GOeIfiiMBqvoHdambQ++B5YinBicrzFjXM47oXFbiY3KjYYUK23JOCVk8Z+zP7fjhO8QPV7t/pXd4dH3kdPD5zkm2Pvg967RtKaqOoglh1QqgLFTOAYOxa4W4ZyeeG1YLczqL3YrwZjvW/43tdE1uMI+XPC6lmfq2RhtAB0/aR7H+TTFmqzajiiB6vcvg0pOj3+rSQ+v3QDzakGoDry6M+FhTz0K/x1MG+M28Z92ZpRnrRXVQ+ngsHmb2WitjALFdVS/PVUOi6G1LXyzLMwV8qMll3FgTMDmC9QxShp/nKj3Mp7y+B+EdpYEVAB2vNy6MrLrekvYv+cFGYmtteaQlRCa8wZMbryTkmSxyNLoa1aXLfF3cvMVxYpngnDyGokpgJQ+uCL7vqzRgvji5WhFfAD5V4=
  app: serene-citadel-94389
  on:
    repo: wjypark94/fridgeful-api
